### ISSUE TITLE
Too many emails

### ISSUE THREAD

**Issue by zachberger** [ritstudentgovernment/petitions#47]
I think you are frustrating a few people tonight with the constant email bombardment. I understand the need to communicate but sending the same email to hundreds of users 30+ times is not the way to do it. Perhaps a single email blast with the update would have been better...

**Comment by petermikitsh** [comment]
I'm open to PR requests :)

**Comment by ShaydeNofziger** [comment]
One way I see to curb the flood of emails might be to implement a periodic newsletter. This newsletter would showcase all new updates to petitions since the previous email. This could be done on a weekly basis, kind of like a weekly update.

If people still would like to receive emails every time a petition they signed is updated, they could "opt-in" (or opt-out) to receiving notifications / weekly newsletters in their Profile page.

**Comment by petermikitsh** [comment]
We've thought about a lot of things. If users were truly upset, then I would suspect than more than 0.15% of them would have disabled e-mail notifications. The average user has signed about 5 petitions; which makes the current "fire-and-forget" strategy (while primitive) acceptable for our current needs. We're exploring a lot of options right now; the idea of a newsletter has been thrown around. 

Currently, there isn't much of a consensus from stakeholders. It's on our radar, but our backlog is already right now.
