### ISSUE TITLE
Add College / School -Specific PawPrints

### ISSUE THREAD

**Issue by KevinMGranger** [ritstudentgovernment/petitions#58]
PawPrints has proven so far that more students are willing be involved, and wish to be informed, about issues facing their campus-- so long as the process is made easy and transparent.

I believe the student body would benefit greatly from applying the same concept to each specific college / school / institute within RIT.

The signature threshold could be based off of the overall size of that college, and voting on it would be limited to members of that college (through major or minor).

Once it warrants a response, the response would come from that college's senator. That senator would then ideally take action with the administrators of that college, and/or bring the issue up at the next senate meeting.

This may be out of scope as a GitHub issue, since this involves SG policy. My apologies if this is not the best place for this. If this would be better served as a PawPrints petition itself, please do say so.

**Comment by petermikitsh** [comment]
For some context, the current workflow for a petition is usually as follows: Once a petition reaches its threshold, an alert is dispatched to SG leadership (President, VP, Director of Student Relations, Director of Services, and myself). The petition is then discussed at the next Senate meeting. A vote is taken by Senate to create a charge, which officially assigns the petition to the most relevant [SG standing committee](https://sg.rit.edu/committees). The standing committee reviews the petition and objectively explores the issue from all angles. Note that the optimal solution may not be what the petitioner's proposed solution to the issue, if one was included in the petition. After this research by the committee is completed, the committee takes action on the issue and gives an update to the Senate. If it is determined by the committee that the petition issue is of great significance to students, the committee may initiate a discussion with Senate before implementing the committee's proposed solution. Given our current workflow, any petition that was specifically regarding a single college would likely be referred to our Academics and Co-op Committee. 

From a technology perspective, this could be a resource-intensive feature request to implement. Our current authentication system doesn't capture which colleges users are from. We would have to periodically update per-college enrollment numbers if the policy is written to say that a "minimum signature threshold" is a percentage of the college's total population, and it would have to override the current default number (200). Anything is possible, of course, with enough time and resources.

From a policy perspective, policy is certainly influenced by petitions. I would recommend posting this to PawPrints because it would be useful to know if a substantial number of students would find this feature to be valuable, prior to SG allocating any resources necessary to implement it. I certainly could see a niche for it since currently PawPrints is predominantly focused on campus-wide issues. This sort of functionality would definitely encourage people to post about relevant issues, but a slightly smaller I'm sitting next to Nick, current Director of Services, and showed him your issue. He thinks it's an interesting idea.

**Comment by KevinMGranger** [comment]
This is all good to know. I certainly figured that interfacing with SIS would be a pain, but that's a bridge that we can burn when we come to it, if people think there's value.

Perhaps the idea of college-specific issues being brought up simply hasn't crossed people's minds? In that case, promotion of that idea is simpler than adding a ton of functionality.

I'll close this for now, until something's decided.

**Comment by petermikitsh** [comment]
In the interim, what would you think of simply adding college-specific tags to PawPrints?

**Comment by KevinMGranger** [comment]
:+1:
